language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - "AUTOMATED_TESTING=1 AUTHOR_TESTING=1 RELEASE_TESTING=1"
install:
  - "cpanm -n Test::More Test::Pod Test::Pod::Coverage Test::CheckManifest"
  - "cpanm -n Test::CPAN::Changes Test::Kwalitee Test::Pod::Spelling::CommonMistakes"
  - "cpanm -n --installdeps ."
script:
  - perl Makefile.PL && make manifest && make test
sudo: false
notifications:
  email: false
